#!/usr/bin/env python3
"""Convert the MSPV item spreadsheet to data/items.js for the item explorer.

Usage:
  python3 tools/convert_items.py [path/to/MSPV_Items_7_27_26.xlsx]

If no path is given, the script looks for the filename named in
tools/config.json ("itemSpreadsheet") in the repo root.

Expected columns (matched loosely, case-insensitive, by keyword):
  item number, description, category, latex-free flag,
  Medline PVON and status, CHS PVON and status,
  contract number, CLIN, effective date, completion date

Requires: pip install openpyxl
"""
import datetime
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
config = json.loads((ROOT / "tools" / "config.json").read_text())

src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / config["itemSpreadsheet"]
if not src.exists():
    sys.exit(f"Spreadsheet not found: {src}\n"
             "Place the MSPV item spreadsheet in the repo root or pass its path.")

try:
    import openpyxl
except ImportError:
    sys.exit("Missing dependency. Run: pip install openpyxl")

wb = openpyxl.load_workbook(src, data_only=True)
ws = wb.active
rows = list(ws.iter_rows(values_only=True))
if not rows:
    sys.exit("Spreadsheet is empty.")

header = [str(c).strip().lower() if c is not None else "" for c in rows[0]]


def col(*keywords, exclude=()):
    for i, name in enumerate(header):
        if all(k in name for k in keywords) and not any(x in name for x in exclude):
            return i
    return None


IDX = {
    "itemNumber": col("item"),
    "description": col("desc"),
    "category": col("categ"),
    "latexFree": col("latex"),
    "medlinePvon": col("medline", "pvon", exclude=("status",)) or col("medline", "pvon"),
    "medlineStatus": col("medline", "status"),
    "chsPvon": col("chs", "pvon", exclude=("status",)) or col("chs", "pvon"),
    "chsStatus": col("chs", "status"),
    "contractNumber": col("contract"),
    "clin": col("clin"),
    "effectiveDate": col("effective"),
    "completionDate": col("completion") or col("ultimate"),
}

missing = [k for k, v in IDX.items() if v is None]
if missing:
    print(f"WARNING: columns not matched, fields will be null: {missing}")
    print(f"Header row seen: {header}")


def cell(row, key):
    i = IDX.get(key)
    if i is None or i >= len(row):
        return None
    v = row[i]
    if isinstance(v, (datetime.date, datetime.datetime)):
        return v.strftime("%Y-%m-%d")
    if v is None:
        return None
    return str(v).strip()


def derive_family(item):
    text = f"{item.get('category') or ''} {item.get('description') or ''}".upper()
    if "LLDPE" in text or "LINEAR" in text or "LOW DENSITY" in text or "LOW-DENSITY" in text:
        return "LLDPE"
    if "HDPE" in text or "HIGH DENSITY" in text or "HIGH-DENSITY" in text:
        return "HDPE"
    return None


SIZE_RE = re.compile(r"(\d{1,3}(?:\.\d+)?\s*[xX]\s*\d{1,3}(?:\.\d+)?)")


def derive_size(item):
    m = SIZE_RE.search(item.get("description") or "")
    return m.group(1).replace(" ", "").upper() if m else None


items = []
for row in rows[1:]:
    if not any(c is not None and str(c).strip() for c in row):
        continue
    item = {k: cell(row, k) for k in IDX}
    item["family"] = derive_family(item)
    item["size"] = derive_size(item)
    items.append(item)

payload = {
    "pending": False,
    "generatedFrom": src.name,
    "generatedAt": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "contractNumber": config["contractNumber"],
    "items": items,
}

out = ROOT / config["itemDataOutput"]
out.write_text(
    "/* Generated by tools/convert_items.py. Do not edit by hand. */\n"
    "window.MSPV_ITEMS = " + json.dumps(payload, indent=2) + ";\n"
)
print(f"{len(items)} items written to {out}")
print("Spot-check against the source spreadsheet before shipping: "
      "row count, one sampled row, and PVON statuses.")
